version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_bot
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - qdrant
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
      
volumes:
  qdrant_data:
